import Head from 'next/head'
import Image from 'next/image'
import Hero from "../component/Hero"
import baseUrl from "../mongoose/config/baseUrl"
import { Container } from 'react-bootstrap';
import style from "../styles/Home.module.css"


export default function Home({user}) {
  return (
    <>
    <section>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className={style.heroSection}>
        <Hero />
      </div>

      {user.map((val, index) => {
        return(
          <>
            <h5 className="text-blue-500" key={index}>{val.title}</h5>
          </>
        )
      })}
    </section>
    </>
  )
}

export const getServerSideProps = async() => {
  const res = await fetch(`${baseUrl}/api/mobile`)
  const user = await res.json()

  return{
    props: {
      user : user
    }
  }
}
