import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home({user}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {user.map((val, index) => {
        return(
          <>
            <h5 key={index}>{val.title}</h5>
          </>
        )
      })}
    </div>
  )
}

export const getServerSideProps = async() => {
  const res = await fetch(`https://next-app-next.herokuapp.com/api/mobile`)
  const user = await res.json()

  return{
    props: {
      user : user
    }
  }
}
